### ISSUE TITLE
Sticky table of contents not working on IE and Edge

### ISSUE THREAD

**Issue by crisbeto** [angular/material.angular.io#285] opened 2017-10-06 17:55 UTC
The table of contents doesn't stick when scrolling on IE and Edge.

**Comment by donroyco** [comment] 2017-10-17 12:02
Related to #257?

**Comment by Splaktar** [comment] 2021-02-06 17:55
Going to close this as a duplicate of https://github.com/angular/material.angular.io/issues/257 as it's not working on Firefox or Chrome either.

**Closed by Splaktar** 2021-02-06 17:55 UTC
Labels: windows
