### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by bobmayuze** [angular/material.angular.io#404] opened 2018-03-07 03:47 UTC
I did npm install inside the root folder, but it doesn't seem to compile when I run ng serve. Here is the error message:

ERROR in node_modules/@angular/material-examples/typings/bottom-sheet-overview/bottom-sheet-overview-example.d.ts(1,10): error TS2305: Module '"/Users/user/Documents/JS/angular/material.angular.io-master/node_modules/@angular/material/material"' has no exported member 'MatBottomSheet'.
node_modules/@angular/material-examples/typings/bottom-sheet-overview/bottom-sheet-overview-example.d.ts(1,26): error TS2305: Module '"/Users/user/Documents/JS/angular/material.angular.io-master/node_modules/@angular/material/material"' has no exported member 'MatBottomSheetRef'.
node_modules/@angular/material-examples/typings/tree-flat-overview/tree-flat-overview-example.d.ts(1,33): error TS2307: Cannot find module '@angular/cdk/tree'.
node_modules/@angular/material-examples/typings/tree-flat-overview/tree-flat-overview-example.d.ts(2,57): error TS2307: Cannot find module '@angular/material/tree'.
node_modules/@angular/material-examples/typings/tree-nested-overview/tree-nested-overview-example.d.ts(1,35): error TS2307: Cannot find module '@angular/cdk/tree'.
node_modules/@angular/material-examples/typings/tree-nested-overview/tree-nested-overview-example.d.ts(2,41): error TS2307: Cannot find module '@angular/material/tree'.

I tried to delete node_modules and re npm install, but it still doesn't work. Any thought?

**Comment by Splaktar** [comment] 2018-04-22 10:10
Going to close this as a dupe of https://github.com/angular/material.angular.io/issues/426 which has a PR now.

**Closed by Splaktar** 2018-04-22 10:10 UTC
