### ISSUE TITLE
Build and run errors, looks like the css files went missing in the assets folder.

### ISSUE THREAD

**Issue by mrtinkz** [angular/material.angular.io#227] opened 2017-07-22 23:20 UTC
`ERROR in multi ./src/assets/pink-bluegrey.css
Module not found: Error: Can't resolve 'C:\opt\workspace\github\material.angular.io\src\assets\pink-bluegrey.css' in 'C:\opt\workspace\github\material.angular.io\node_modules\@angular\cli\models\webpack-configs'
 @ multi ./src/assets/pink-bluegrey.css

ERROR in multi ./src/assets/deeppurple-amber.css
Module not found: Error: Can't resolve 'C:\opt\workspace\github\material.angular.io\src\assets\deeppurple-amber.css' in 'C:\opt\workspace\github\material.angular.io\node_modules\@angular\cli\models\webpack-configs'
 @ multi ./src/assets/deeppurple-amber.css

ERROR in multi ./src/assets/indigo-pink.css
Module not found: Error: Can't resolve 'C:\opt\workspace\github\material.angular.io\src\assets\indigo-pink.css' in 'C:\opt\workspace\github\material.angular.io\node_modules\@angular\cli\models\webpack-configs'
 @ multi ./src/assets/indigo-pink.css

ERROR in multi ./src/assets/purple-green.css
Module not found: Error: Can't resolve 'C:\opt\workspace\github\material.angular.io\src\assets\purple-green.css' in 'C:\opt\workspace\github\material.angular.io\node_modules\@angular\cli\models\webpack-configs'
 @ multi ./src/assets/purple-green.css`

**Comment by chrisformula** [comment] 2017-07-26 07:43
Having the same issue but with extras:

ERROR in /material.angular.io-master/src/app/shared/example-viewer/example-viewer.ts (5,47): Cannot find module '@angular/material-examples'.

ERROR in /material.angular.io-master/src/app/shared/plunker/plunker-writer.ts (3,27): Cannot find module '@angular/material-examples'.

ERROR in /material.angular.io-master/src/app/shared/plunker/plunker-button.ts (3,27): Cannot find module '@angular/material-examples'.

ERROR in /material.angular.io-master/src/app/app-module.ts (9,29): Cannot find module '@angular/material-examples'.

ERROR in /material.angular.io-master/src/app/pages/component-viewer/component-viewer.spec.ts (7,34): Cannot find module '@angular/material-examples'.

ERROR in /material.angular.io-master/src/app/shared/example-viewer/example-viewer.spec.ts (4,34): Cannot find module '@angular/material-examples'.

ERROR in /material.angular.io-master/src/app/shared/plunker/plunker-writer.spec.ts (8,27): Cannot find module '@angular/material-examples'.

ERROR in Error encountered resolving symbol values statically. Could not resolve @angular/material-examples relative to /material.angular.io-master/src/app/app-module.ts., resolving symbol AppModule in /material.angular.io-master/src/app/app-module.ts, resolving symbol AppModule in /material.angular.io-master/src/app/app-module.ts

ERROR in multi ./src/assets/pink-bluegrey.css
Module not found: Error: Can't resolve '/material.angular.io-master/src/assets/pink-bluegrey.css' in '/material.angular.io-master/node_modules/@angular/cli/models/webpack-configs'
 @ multi ./src/assets/pink-bluegrey.css

ERROR in multi ./src/assets/deeppurple-amber.css
Module not found: Error: Can't resolve '/material.angular.io-master/src/assets/deeppurple-amber.css' in '/material.angular.io-master/node_modules/@angular/cli/models/webpack-configs'
 @ multi ./src/assets/deeppurple-amber.css

ERROR in multi ./src/assets/indigo-pink.css
Module not found: Error: Can't resolve '/material.angular.io-master/src/assets/indigo-pink.css' in '/material.angular.io-master/node_modules/@angular/cli/models/webpack-configs'
 @ multi ./src/assets/indigo-pink.css

ERROR in multi ./src/assets/purple-green.css
Module not found: Error: Can't resolve '/material.angular.io-master/src/assets/purple-green.css' in '/material.angular.io-master/node_modules/@angular/cli/models/webpack-configs'
 @ multi ./src/assets/purple-green.css

ERROR in ./src/app/app-module.ts
Module not found: Error: Can't resolve '@angular/material-examples' in '/material.angular.io-master/src/app'
 @ ./src/app/app-module.ts 15:0-59
 @ ./src/app/index.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts

ERROR in ./src/app/shared/plunker/plunker-button.ts
Module not found: Error: Can't resolve '@angular/material-examples' in '/material.angular.io-master/src/app/shared/plunker'
 @ ./src/app/shared/plunker/plunker-button.ts 12:0-57
 @ ./src/app/app-module.ts
 @ ./src/app/index.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts

ERROR in ./src/app/shared/example-viewer/example-viewer.ts
Module not found: Error: Can't resolve '@angular/material-examples' in '/material.angular.io-master/src/app/shared/example-viewer'
 @ ./src/app/shared/example-viewer/example-viewer.ts 13:0-64
 @ ./src/app/shared/doc-viewer/doc-viewer-module.ts
 @ ./src/app/app-module.ts
 @ ./src/app/index.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts

**Comment by androidovshchik** [comment] 2017-09-26 15:31
Simply fix paths in `angular-cli.json`
```
"styles": [
  "main.scss",
  "highlightjs/material-light.css",
  {"input": "assets/custom-themes/pink-bluegrey.scss", "lazy": true},
  {"input": "assets/custom-themes/deeppurple-amber.scss", "lazy": true},
  {"input": "assets/custom-themes/indigo-pink.scss", "lazy": true},
  {"input": "assets/custom-themes/purple-green.scss", "lazy": true}
],
```

**Comment by dapojaja** [comment] 2017-10-07 12:25
@androidovshchik Big thanks

**Comment by wangjian1119** [comment] 2017-11-25 05:09
@androidovshchik  that's right，but how did the author make such a mistake? @mprobst

**Comment by Splaktar** [comment] 2018-04-22 10:50
This may be caused by not building the themes. I put the steps you need to run locally in https://github.com/angular/material.angular.io/issues/425#issuecomment-383369260.

**Closed by Splaktar** 2018-04-22 10:50 UTC
Labels: cannot reproduce
