### ISSUE TITLE
material.angular.io  repo on start dumps error as belwo

### ISSUE THREAD

**Issue by kushwahashiv** [angular/material.angular.io#369] opened 2018-01-09 17:56 UTC
When I run the command start it and open in browser http://localhost:4200/
I get following error:

any help to resolve would be appreciated

```cmd
/usr/local/bin/node /usr/local/lib/node_modules/npm/bin/npm-cli.js run start --scripts-prepend-node-path=auto

> material-angular-io@0.0.0 start /Users/Shiv/projects/material.angular.io
> npm run build-themes && ng serve --aot --sourcemaps=false


> material-angular-io@0.0.0 build-themes /Users/Shiv/projects/material.angular.io
> bash ./tools/build-themes.sh

Building custom theme scss files.
Finished building CSS.
** NG Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
Date: 2018-01-09T17:53:12.595Z

Hash: 3fb6c376ecd5c0d526c2
ERROR in : Can't export value MatDividerModule in /Users/Shiv/projects/material.angular.io/node_modules/@angular/material/material.d.ts from ɵel in /Users/Shiv/projects/material.angular.io/node_modules/@angular/material-examples/typings/index.d.ts as it was neither declared nor imported!Time: 7966
ms
: TypeError: Cannot read property 'flags' of undefinedchunk {
assets/deeppurple-amber}     at checkUnreachable (/Users/Shiv/projects/material.angular.io/node_modules/typescript/lib/typescript.js:24905:31)assets/deeppurple-amber.bundle.js
 (assets/deeppurple-amber) 56.7 kB [initial]    at bindChildrenWorker (/Users/Shiv/projects/material.angular.io/node_modules/typescript/lib/typescript.js:23111:17) [rendered]

chunk {    at bindChildren (/Users/Shiv/projects/material.angular.io/node_modules/typescript/lib/typescript.js:23055:17)assets/indigo-pink
} assets/indigo-pink.bundle.js    at bind (/Users/Shiv/projects/material.angular.io/node_modules/typescript/lib/typescript.js:24319:21) (assets/indigo-pink) 56.6 kB 
[initial] [rendered]    at bindSourceFile (/Users/Shiv/projects/material.angular.io/node_modules/typescript/lib/typescript.js:22689:17)

chunk {assets/pink-bluegrey}     at Object.bindSourceFile (/Users/Shiv/projects/material.angular.io/node_modules/typescript/lib/typescript.js:22640:9)assets/pink-bluegrey.bundle.js (assets/pink-bluegrey) 58.3 kB [initial]
 [rendered]
    at initializeTypeChecker (/Users/Shiv/projects/material.angular.io/node_modules/typescript/lib/typescript.js:47988:20)chunk {assets/purple-green
} assets/purple-green.bundle.js (assets/purple-green) 58.6 kB     at Object.createTypeChecker (/Users/Shiv/projects/material.angular.io/node_modules/typescript/lib/typescript.js:27142:9)[initial] [rendered]

chunk {inline    at getDiagnosticsProducingTypeChecker (/Users/Shiv/projects/material.angular.io/node_modules/typescript/lib/typescript.js:69678:93)} 
inline.bundle.js (inline) 5.79 kB [entry]    at /Users/Shiv/projects/material.angular.io/node_modules/typescript/lib/typescript.js:69809:35 [rendered]

chunk {main    at runWithCancellationToken (/Users/Shiv/projects/material.angular.io/node_modules/typescript/lib/typescript.js:69779:24)} 
main.bundle.js (main) 1.01 kB [initial]    at getSemanticDiagnosticsForFileNoCache (/Users/Shiv/projects/material.angular.io/node_modules/typescript/lib/typescript.js:69802:20) [rendered]

chunk {    at getAndCacheDiagnostics (/Users/Shiv/projects/material.angular.io/node_modules/typescript/lib/typescript.js:70033:26)styles
} styles.bundle.js (styles) 84.6 kB     at getSemanticDiagnosticsForFile (/Users/Shiv/projects/material.angular.io/node_modules/typescript/lib/typescript.js:69799:20)[initial]
 [rendered]
    at getDiagnosticsHelper (/Users/Shiv/projects/material.angular.io/node_modules/typescript/lib/typescript.js:69738:24)chunk {
vendor} vendor.bundle.js    at Object.getSemanticDiagnostics (/Users/Shiv/projects/material.angular.io/node_modules/typescript/lib/typescript.js:69751:20) (vendor) 323 kB 
[initial] [rendered]    at /Users/Shiv/projects/material.angular.io/node_modules/@angular/compiler-cli/src/transformers/program.js:120:57

    at Array.forEach (<anonymous>)
    at AngularCompilerProgram.getTsSemanticDiagnostics (/Users/Shiv/projects/material.angular.io/node_modules/@angular/compiler-cli/src/transformers/program.js:118:21)
    at Object.gatherDiagnostics (/Users/Shiv/projects/material.angular.io/node_modules/@angular/cli/node_modules/@ngtools/webpack/src/gather_diagnostics.js:60:45)
    at AngularCompilerPlugin._emit (/Users/Shiv/projects/material.angular.io/node_modules/@angular/cli/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:739:65)
    at Promise.resolve.then.then.then (/Users/Shiv/projects/material.angular.io/node_modules/@angular/cli/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:578:54)

webpack: Failed to compile.

webpack: Compiling...
webpack: wait until bundle finished: /
Date: 
2018-01-09T17:53:14.679ZERROR in : Can't export value MatDividerModule in /Users/Shiv/projects/material.angular.io/node_modules/@angular/material/material.d.ts from ɵel in /Users/Shiv/projects/material.angular.io/node_modules/@angular/material-examples/typings/index.d.ts as it was neither declared nor imported!

Hash: 
c14f46ebe87a876d8050
Time: 1547ms
chunk {assets/deeppurple-amber} assets/deeppurple-amber.bundle.js (assets/deeppurple-amber) 56.7 kB [initial]
chunk {assets/indigo-pink} assets/indigo-pink.bundle.js (assets/indigo-pink) 56.6 kB [initial]
chunk {assets/pink-bluegrey} assets/pink-bluegrey.bundle.js (assets/pink-bluegrey) 58.3 kB [initial]
chunk {assets/purple-green} assets/purple-green.bundle.js (assets/purple-green) 58.6 kB [initial]
chunk {inline} inline.bundle.js (inline) 5.79 kB [entry]
chunk {main} main.bundle.js (main) 1.01 kB [initial]
chunk {styles} styles.bundle.js (styles) 84.6 kB [initial]
chunk {vendor} vendor.bundle.js (vendor) 323 kB [initial]

webpack: Failed to compile.
/Users/Shiv/projects/material.angular.io/node_modules/typescript/lib/typescript.js:69795
                throw e;
                ^

TypeError: Cannot read property 'flags' of undefined
    at checkUnreachable (/Users/Shiv/projects/material.angular.io/node_modules/typescript/lib/typescript.js:24905:31)
    at bindChildrenWorker (/Users/Shiv/projects/material.angular.io/node_modules/typescript/lib/typescript.js:23111:17)
    at bindChildren (/Users/Shiv/projects/material.angular.io/node_modules/typescript/lib/typescript.js:23055:17)
    at bind (/Users/Shiv/projects/material.angular.io/node_modules/typescript/lib/typescript.js:24319:21)
    at bindSourceFile (/Users/Shiv/projects/material.angular.io/node_modules/typescript/lib/typescript.js:22689:17)
    at Object.bindSourceFile (/Users/Shiv/projects/material.angular.io/node_modules/typescript/lib/typescript.js:22640:9)
    at initializeTypeChecker (/Users/Shiv/projects/material.angular.io/node_modules/typescript/lib/typescript.js:47988:20)
    at Object.createTypeChecker (/Users/Shiv/projects/material.angular.io/node_modules/typescript/lib/typescript.js:27142:9)
    at getDiagnosticsProducingTypeChecker (/Users/Shiv/projects/material.angular.io/node_modules/typescript/lib/typescript.js:69678:93)
    at /Users/Shiv/projects/material.angular.io/node_modules/typescript/lib/typescript.js:69809:35

```

**Comment by amcdnl** [comment] 2018-02-10 17:09
Dupe of #382

**Closed by amcdnl** 2018-02-10 17:09 UTC
