### ISSUE TITLE
Sample App Example on Getting Started Page

### ISSUE THREAD

**Issue by psingl** [angular/material.angular.io#139] opened 2017-04-04 02:56 UTC
I was just going through the Angular Material documentation at https://material.angular.io I noticed on Getting Started page there were few App Demo Links given at the end of the page. On clicking either of the links on Getting Started page for app demo these links redirect the user back to https://material.angular.io without showing any data and disabling all the links. Let me explain with the help of screenshots.
1. Click on either of the links below. Through this screenshot I wanted to show that when we hover on the first link i.e. Material Sample App, it is not like that we are clicking on some wrong link checkout second screenshot in this step only
![image](https://cloud.githubusercontent.com/assets/13885706/24639728/640720c2-190f-11e7-8496-2f8e75192547.png)
![image](https://cloud.githubusercontent.com/assets/13885706/24639856/43716826-1910-11e7-846e-c86c1963107c.png)
2. It starts showing something like this
![image](https://cloud.githubusercontent.com/assets/13885706/24639744/86ca2942-190f-11e7-9b08-7c6a1bda1fd0.png)
3. Now if you try to click on any of the links given in the navbar, it does not perform any of the action. It keeps on showing the page as shown in step 2
4. If you press F5 i.e. reload that page without making any changes in the address we were redirected to it shows the starting page as shown
![image](https://cloud.githubusercontent.com/assets/13885706/24639781/cde44b0a-190f-11e7-8d1a-8c3fc4de3edd.png)

Similarly, there is an issue with the second sample app link.

**Comment by Chan4077** [comment] 2017-04-04 16:08
Duplicate of #105.

**Closed** 2017-06-07 21:53 UTC
