### ISSUE TITLE
Unable to go to CDK docs after visiting component overview.

### ISSUE THREAD

**Issue by mmalerba** [angular/material.angular.io#416] opened 2018-03-20 21:49 UTC
Repro steps:
- Go to any component overview (e.g. https://material.angular.io/components/autocomplete/overview)
- Try to navigate to the CDK docs by pressing the "CDK" button in the top nav
- You get navigated to https://material.angular.io/components/categories instead, further attempts to click the button still don't take you to the CDK docs

Strangely it works fine if you don't go to a component overview first. (e.g. try visiting https://material.angular.io/components/categories directly and navigating to CDK from there, it works fine).

**Comment by Splaktar** [comment] 2018-04-22 10:15
Dupe of https://github.com/angular/material.angular.io/issues/327. Fixed in https://github.com/angular/material.angular.io/pull/410.

**Closed by Splaktar** 2018-04-22 10:15 UTC
