### ISSUE TITLE
'Edit in Plunker' not working

### ISSUE THREAD

**Issue by jurafa** [angular/material.angular.io#202] opened 2017-06-27 07:38 UTC
The buttons 'Edit in Plunker' in 'Example' section redirect to Plunker that only shows message 'Loading Material Docs example...' but nothing else happenes.

**Comment by jelbourn** [comment] 2017-07-10 19:05
Should all be fixed now.

**Closed by jelbourn** 2017-07-10 19:05 UTC

**Comment by akaztp** [comment] 2017-10-07 16:30
At this moment, all examples (at least the bunch I've tried) in plunker not working.
They are like @jurafa indicates and the error on console is:
```
Error: (SystemJS) Unexpected value 'undefined' exported by the module 'PlunkerMaterialModule'
	Error: Unexpected value 'undefined' exported by the module 'PlunkerMaterialModule'	   
```

Your are probably aware of this since the problem is with the renaming of MdXXXX to MatXXX.
In file main.ts on the plunker, replace all "Md" by "Mat" and the plunker starts working again.
