### ISSUE TITLE
Angular Material website is not loading

### ISSUE THREAD

**Issue by Murali2807** [angular/material.angular.io#1275] opened 2024-10-14 03:40 UTC
Angular Material website is not loading 

![Image](https://github.com/user-attachments/assets/5c458b76-bd3a-497b-b578-caff05e5c82f)

**Comment by amysorto** [comment] 2024-10-31 15:27
Hi @Murali2807, I am unable to reproduce this so I will close this issue. If this is still happening, please create a new issue with more information.

**Closed by amysorto** 2024-10-31 15:27 UTC
