### ISSUE TITLE
https://material.angular.io/ -- This site can’t be reached

### ISSUE THREAD

**Issue by Sujaydasarathi** [angular/material.angular.io#472] opened 2018-06-11 12:43 UTC
I am not able to reach the site https://material.angular.io/ for the past few days...
 Location Australia / Melbourne...

**Comment by Sujaydasarathi** [comment] 2018-06-11 13:12
A temporary fix is available @ https://github.com/angular/material.angular.io/issues/436

Benjamin Schäublin's suggestion helped me (@bschaeublin)

**Comment by Splaktar** [comment] 2019-08-12 14:35
What web browser? Is this still a recurring issue?

This seems like a duplicate of #436.

**Closed by Splaktar** 2019-08-12 14:35 UTC
