### ISSUE TITLE
Error when navigating from heading id

### ISSUE THREAD

**Issue by ultreson** [angular/material.angular.io#499] opened 2018-08-06 20:31 UTC
when the page is loaded, navigating to
https://material.angular.io/components/table/overview#sorting
works and takes you to the header.

But opening a new tab with the link doesn't place you where the id is because it wasnt loaded yet
so you end up on the top of the page when clicking the heading links to a new tab.

**Comment by DevVersion** [comment] 2018-09-12 14:10
Duplicate of #396

**Closed by DevVersion** 2018-09-12 14:10 UTC
