### ISSUE TITLE
Theme picker bugs on mobile

### ISSUE THREAD

**Issue by philip-firstorder** [angular/material.angular.io#495] opened 2018-08-02 21:20 UTC
On mobile devices (iPhone 7, iPhone X, Chrome, Safari) the theme picker doesn't automatically close.
And then if you insist in clicking it it even renders weird like in this picture.

Notice how I selected the upper left theme but theme remains the same.

Only after a full page refresh I am able to change the theme again, but after the first tap is doesn't respond anymore.

![image-1](https://user-images.githubusercontent.com/30979663/43611721-5eba8d56-96aa-11e8-9ffa-e86ecdb4101e.jpg)

**Comment by Splaktar** [comment] 2020-05-21 13:44
I cannot reproduce this on an iPad on `13.4.1` in Chrome or Safari.

Can you please provide more details/screenshots/reproduction steps of this issue with the new theme picker?

**Comment by philip-firstorder** [comment] 2020-05-21 20:17
Here's what you need to do to reproduce it:
1) Clear the cache of your Safari browser, so that no theme is loaded yet, this is very important because the initial loading time will cause the problem
2) Click on the theme button, if your cache is cleared then no option is selected, which you might want to also fix by selecting a default theme
![319E65B3-D2AD-4387-B359-3D423321D52D](https://user-images.githubusercontent.com/30979663/82601944-9daafe80-9bb0-11ea-912f-410ab655597f.png)

3) Click on a theme, then try to change it, you should get this extra overlay to the left
![FF658396-C26C-4010-9E56-05D625055649](https://user-images.githubusercontent.com/30979663/82601989-abf91a80-9bb0-11ea-80aa-8e3d58c70798.png)

**Comment by Splaktar** [comment] 2020-05-26 22:01
Thank you for the additional details. I'm able to reproduce the issue with not having a default theme selected in the drop down after clearing cache.

However, I'm not able to reproduce the issue with the blank overlay on my iPad. I'll have to try an iPhone emulator.

**Comment by philip-firstorder** [comment] 2020-05-26 23:50
Yeah that's why I put at the beginning of this issue that it only appears on mobile devices (iPhone 7, iPhone X, Chrome, Safari). I don't have a tablet to test but on iMac or MacBook it doesn't happen.

I just reproduced on the xCode Simulator on my iMac, so you should also be able to debug it using the Safari Inspector.
<img width="487" alt="Screenshot 2020-05-27 at 01 48 29" src="https://user-images.githubusercontent.com/30979663/82961005-66778b80-9fbc-11ea-8568-624bbc6c9a9e.png">

**Comment by amysorto** [comment] 2024-06-03 20:41
I cannot reproduce this issue for v18 on an iPhone, so I'm closing this issue

**Closed by amysorto** 2024-06-03 20:41 UTC
Labels: P4: nice to have, effort1: easy (hours), good for community contribution
