### ISSUE TITLE
bug(text-field): When the mobile keyboard hides the text-field example, the text is written backwards, cursor positioning problem.

### ISSUE THREAD

**Issue by julietafrade97** [angular/material.angular.io#919] opened 2021-01-27 19:09 UTC
# 📚 Docs or angular.io bug report

### Description
When trying the input fields examples in mobile horizontal direction and the mobile keyboard hides de input that is being tested, the text appears written backwards. This happens because the cursor stays in the start of the string instead of the end.

### What's the affected URL?**
https://material.angular.io/cdk/text-field/examples

### Reproduction Steps**
1 - Open https://material.angular.io/cdk/text-field/examples on mobile
2 - The keyboard must be big enough to hide the input
3 - Write in any of the examples "1234"

### Expected vs Actual Behavior**
**Expected:** The text written is "1234"
**Actual:** The text written is "4321"

## 📷Screenshot
**The keyboard hiding the input:**
![image](https://user-images.githubusercontent.com/19336587/106040103-e026c280-60d1-11eb-8961-ffc9addad772.png)

**The result after typing "1234":**
![image](https://user-images.githubusercontent.com/19336587/106040127-e74dd080-60d1-11eb-8378-7a4cb0aa826e.png)

**The result after typing "12348" in case the keyboard is not hiding the input:**
![image](https://user-images.githubusercontent.com/19336587/106040141-eddc4800-60d1-11eb-9dbe-bbed50e426c8.png)

**The result after typing "123" in case the keyboard is not hiding the input:**
![image](https://user-images.githubusercontent.com/19336587/106040863-ec5f4f80-60d2-11eb-8314-945189c607c7.png)

### Browser info
Chrome for Android: 88.0.4324.93

**Comment by Splaktar** [comment] 2021-02-16 19:16
@julietafrade97 can you please provide the device manufacturer, model, and Android version?

**Comment by Splaktar** [comment] 2021-02-16 19:27
I am not able to reproduce this on https://material.angular.io/ with version 11.2.0 or on my local network running the site in dev mode with a Google Pixel 3 with Android 11. I tried with and without the number pad using the Swiftkey keyboard. I tried with the text field barely visible on the bottom of the screen, top of the screen, and in the middle of the screen before tapping the input. It was always the same, correct behavior for me.

That also raises the question, @julietafrade97 what keyboard app are you using?

**Comment by julietafrade97** [comment] 2021-02-16 19:36
> @julietafrade97 can you please provide the device manufacturer, model, and Android version?

I'm using a One Plus 6t with Android 10

**Comment by julietafrade97** [comment] 2021-02-16 19:40
> I am not able to reproduce this on https://material.angular.io/ with version 11.2.0 or on my local network running the site in dev mode with a Google Pixel 3 with Android 11. I tried with and without the number pad using the Swiftkey keyboard. I tried with the text field barely visible on the bottom of the screen, top of the screen, and in the middle of the screen before tapping the input. It was always the same, correct behavior for me.
> 
> That also raises the question, @julietafrade97 what keyboard app are you using?

I'm using the the default keyboard app and that's Gboard. Have in mind that I asked other people with different devices than me to reproduce it and, in the devices that the input was hidden because of the keyboard, it was reproducible. In your case when the keyboard appears does it hide the input?

**Comment by Splaktar** [comment] 2021-02-16 19:42
I also tested this on an iPad with iPadOS 14.4 and I was unable to reproduce it.

Unfortunately, I don't have access to a One Plus device.

**Comment by Splaktar** [comment] 2021-02-16 19:44
![Screenshot_20210216-144133.png](https://user-images.githubusercontent.com/3506071/108113214-38177000-7065-11eb-8cd6-9f3e98e22caf.png)

It mostly makes it hard to see, but I still see the ink bar and the input is just behind the toolbar, but not offscreen.

**Comment by Splaktar** [comment] 2021-02-16 19:46
I expanded my keyboard a bit to fully cover the input, but it still came out 1234. I will try Gboard. ![Screenshot_20210216-144441.png](https://user-images.githubusercontent.com/3506071/108113564-ad834080-7065-11eb-8897-f3c02f8b151d.png)

**Comment by julietafrade97** [comment] 2021-02-16 19:51
I noticed that at the time I tried with the Angular version 11.1.0. Right now I can't reproduce it in 11.2.0 but I can in the older versions, for example, in version 10: https://v10.material.angular.io/components/input/overview. Can you also try in version 10?
Also, can you tell me what changed from 11.1.0 to 11.2.0 that could have fixed this?

**Comment by Splaktar** [comment] 2021-02-16 19:53
![Screenshot_20210216-145227.png](https://user-images.githubusercontent.com/3506071/108114344-af013880-7066-11eb-9c56-6e365ed7b0d4.png)

I saw the same results with Gboard. It came out 1234.

**Comment by Splaktar** [comment] 2021-02-16 19:56
Indeed! I can reproduce this with both SwiftKey and Gboard on https://v10.material.angular.io/! But it does seem to be fixed in v11. Good news!

I'll have to try to dig through the commits to find which one changed this later since I have to jump into a meeting now.

Thank you for your help in investigating this!

**Comment by Splaktar** [comment] 2021-03-01 19:18
I went through the changelog but I wasn't able to find a specific change that was meant to solve this. It might have just been solved as a side-effect of another change to `form-field` or to our docs site (like the changes to do less absolute positioning).

**Closed by Splaktar** 2021-03-01 19:18 UTC
Labels: P3: important
